### ToDo

- [ ] load stl
- [ ] create bounding box + AABB algo
- [ ] calculate center of mass
- [ ] place 1. stl object into middle (by center of mass)
- [ ] randomly place 2. object:
      y ^
      |
      |
      ------>
      | x

- move only x, y and rotate on x-y-plane
- remove all objects which are out of plane (AABB)
- get all distancs of center of mass
- take closest object (by center of mass), check for collision by AABB -> if none use it / if yes -> check for triangle collisions -> if yes take next (repeat) -> if none stop


## Install dependencies


In [1]:
%pip install numpy plotly

Note: you may need to restart the kernel to use updated packages.


## Read STL file's


In [6]:
from read_stl import read_stl_file

# First STL file
faces1, vertices1 = read_stl_file("../cube.stl")

# Second STL file
faces2, vertices2 = read_stl_file("../cube.stl")

In [5]:
print("Faces:", faces.shape)
print("Vertices:", vertices.shape)

print("Shape 1: ", faces[0].shape)
print("Data 1:", faces[0])
print("Shape 2: ", faces[1].shape)
print("Data 2: ", faces[1])

separating_axis_theorem(faces[0], faces[1])

Faces: (12, 3, 3)
Vertices: (8, 3)
Shape 1:  (3, 3)
Data 1: [[0. 4. 6.]
 [2. 0. 6.]
 [2. 4. 6.]]
Shape 2:  (3, 3)
Data 2:  [[2. 0. 6.]
 [0. 4. 6.]
 [0. 0. 6.]]


True